spring:
  datasource:
    url: jdbc:postgresql://10.140.0.3:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update